/* eslint-disable */
import { loadStyles } from '@microsoft/load-themed-styles';
loadStyles([{"rawString":".root_1d115b8f{min-width:260px}.actionButton_1d115b8f{background:0 0;background-color:transparent;border:0;cursor:pointer;margin:0;padding:0;position:relative;width:100%;font-size:12px}html[dir=ltr] .actionButton_1d115b8f{text-align:left}html[dir=rtl] .actionButton_1d115b8f{text-align:right}.actionButton_1d115b8f:hover{background-color:"},{"theme":"neutralLighter","defaultValue":"#f3f2f1"},{"rawString":";cursor:pointer}.actionButton_1d115b8f:active,.actionButton_1d115b8f:focus{background-color:"},{"theme":"themeLight","defaultValue":"#c7e0f4"},{"rawString":"}.actionButton_1d115b8f .ms-Button-icon{font-size:16px;width:25px}.actionButton_1d115b8f .ms-Button-label{margin:0 4px 0 9px}html[dir=rtl] .actionButton_1d115b8f .ms-Button-label{margin:0 9px 0 4px}.buttonSelected_1d115b8f{background-color:"},{"theme":"themeLighter","defaultValue":"#deecf9"},{"rawString":"}.buttonSelected_1d115b8f:hover{background-color:"},{"theme":"themeLight","defaultValue":"#c7e0f4"},{"rawString":";cursor:pointer}@media screen and (-ms-high-contrast:active){.buttonSelected_1d115b8f:hover{background-color:Highlight;color:HighlightText}}@media screen and (-ms-high-contrast:active){.buttonSelected_1d115b8f{background-color:Highlight;color:HighlightText;-ms-high-contrast-adjust:none}}.suggestionsTitle_1d115b8f{font-size:12px}.suggestionsSpinner_1d115b8f{margin:5px 0;white-space:nowrap;line-height:20px;font-size:12px}html[dir=ltr] .suggestionsSpinner_1d115b8f{padding-left:14px}html[dir=rtl] .suggestionsSpinner_1d115b8f{padding-right:14px}html[dir=ltr] .suggestionsSpinner_1d115b8f{text-align:left}html[dir=rtl] .suggestionsSpinner_1d115b8f{text-align:right}.suggestionsSpinner_1d115b8f .ms-Spinner-circle{display:inline-block;vertical-align:middle}.suggestionsSpinner_1d115b8f .ms-Spinner-label{display:inline-block;margin:0 10px 0 16px;vertical-align:middle}html[dir=rtl] .suggestionsSpinner_1d115b8f .ms-Spinner-label{margin:0 16px 0 10px}.itemButton_1d115b8f{height:100%;width:100%;padding:7px 12px}@media screen and (-ms-high-contrast:active){.itemButton_1d115b8f{color:WindowText}}.screenReaderOnly_1d115b8f{position:absolute;width:1px;height:1px;padding:0;margin:-1px;overflow:hidden;clip:rect(0,0,0,0);border:0}"}]);
export const root = "root_1d115b8f";
export const actionButton = "actionButton_1d115b8f";
export const buttonSelected = "buttonSelected_1d115b8f";
export const suggestionsTitle = "suggestionsTitle_1d115b8f";
export const suggestionsSpinner = "suggestionsSpinner_1d115b8f";
export const itemButton = "itemButton_1d115b8f";
export const screenReaderOnly = "screenReaderOnly_1d115b8f";